#!/usr/bin/env sh
# Regenerates the CRDs shipped with the Helm chart from the Rust types.
set -eu
cd "$(dirname "$0")/.."
out=charts/kube-hardware-autoscaler/crds/hardware-autoscaler.safewords.com.yaml
{
  echo "# Generated by hack/gen-crds.sh from src/crd.rs - do not edit."
  cargo run --quiet -- crds
} > "$out"
echo "wrote $out"
