{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-hardware-autoscaler.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-hardware-autoscaler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  selector:
    {{- include "kube-hardware-autoscaler.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.operator.metricsPort }}
      targetPort: metrics
      protocol: TCP
{{- end }}
{{- if .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kube-hardware-autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-hardware-autoscaler.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "kube-hardware-autoscaler.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
